# Generated by Django 2.0.13 on 2021-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='DumbCalls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='FatCalls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='StupidCalls',
            field=models.IntegerField(default=0),
        ),
    ]
